"
" Gustavo Paulo <gustavo.paulo.segura@gmail.com>
" vimrc configuration

"" initial config
set nocompatible
set nowrap
set encoding=utf8
set backspace=indent,eol,start
execute pathogen#infect()
syntax on
filetype plugin indent on

"" mappings config
map <C-n> :NERDTreeToggle<CR>
map <C-m> :TagbarToggle<CR>

"" general config
let mapleader = ","
set number
set ruler
set tabstop=2
set shiftwidth=2
set smarttab
set expandtab
set laststatus=2
set cursorline

"" styling
set guifont=Knack\ Nerd\ Font\ Regular\ 10
set t_Co=256
set background=dark
colorscheme badwolf

if (has("termguicolors"))
  set termguicolors
endif

"" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1

"" vim-airline
let g:airline_powerline_fonts = 1
let g:airline_theme='badwolf'
let g:airline#extensions#tabline#enabled = 1

"" supertab
let g:SuperTabDefaultCompletionType = "<C-X><C-O>"

"" shortcuts
nnoremap <Leader>w :w<CR>

