"
" Gustavo Paulo <gustavo.paulo.segura@gmail.com>
" vimrc basic configuration

"" initial config
set nocompatible
set nowrap
set encoding=utf8
set backspace=indent,eol,start
syntax on
filetype plugin indent on

"" general config
let mapleader = ","
set number
set ruler
set tabstop=2
set shiftwidth=2
set smarttab
set expandtab

"" styling
set guifont=Knack\ Nerd\ Font\ Regular\ 10
set t_Co=256
set background=dark
colorscheme desert

if (has("termguicolors"))
  set termguicolors
endif

