#
# Gustavo Paulo <gustavo.paulo.segura@gmail.com>
#
# Zsh Config
#

## initializing
export ZSH_DISABLE_COMPFIX=true
export ZSH=/home/gpaulo00/.oh-my-zsh
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
  source /etc/profile.d/vte.sh
fi

# basic
DISABLE_AUTO_TITLE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd/mm/yyyy"

# use powerlevel9k and some plugins
plugins=(git rvm systemadmin zsh-autosuggestions)
ZSH_THEME="powerlevel9k/powerlevel9k"

# use simpler theme on tty
if [ "$TERM" = "linux" ]; then
  ZSH_THEME="fishy"
fi

## configure powerlevel9k
# fish-like path
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

# general
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_STATUS_VERBOSE="false"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)
POWERLEVEL9K_HOME_ICON=""
POWERLEVEL9K_HOME_SUB_ICON=""
POWERLEVEL9K_FOLDER_ICON=""

# colors
#POWERLEVEL9K_RVM_BACKGROUND="197"
#POWERLEVEL9K_RVM_FOREGROUND="232"
POWERLEVEL9K_OS_ICON_BACKGROUND="249"
POWERLEVEL9K_OS_ICON_FOREGROUND="black"
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="249"
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="black"

## run Oh My Zsh!
source $ZSH/oh-my-zsh.sh

## my config
export EDITOR=nvim
export WINEARCH=win32
alias vim=$EDITOR
alias zshconfig="${EDITOR} ~/.zshrc"
alias ohmyzsh="${EDITOR} ~/.oh-my-zsh"

## metasploit framework
export MSFSOURCES="/opt"
alias msfconsole="pushd $MSFSOURCES && ./msfconsole && popd"
alias msfvenom="pushd $MSFSOURCES && ./msfvenom && popd"
alias msfrpc="pushd $MSFSOURCES && ./msfrpc && popd"
alias msfrpcd="pushd $MSFSOURCES && ./msfrpcd && popd"

## fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# programming languagues
## Go
export GOPATH=$(go env GOPATH)
export PATH=$PATH:/usr/lib/go-tip/bin:$GOPATH/bin
export LGOPATH=/files/respaldos/.lgo

## Rust
# export PATH=$PATH:$HOME/.cargo/bin

## Python
export PATH="/home/gpaulo00/anaconda3/bin:$PATH"
. ~/anaconda3/etc/profile.d/conda.sh
export PYTHONPATH="$PYTHONPATH:/home/gpaulo00/anaconda3/lib/python3.6/site-packages"

## JavaScript
export NVM_DIR="$(realpath $HOME)/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

## PHP
export PATH="$PATH:$HOME/.config/composer/vendor/bin"

## Java or JVM
export JAVA_HOME="/usr/lib/jvm/java-8-oracle/"
export SDKMAN_DIR="/home/gpaulo00/.sdkman"
[[ -s "/home/gpaulo00/.sdkman/bin/sdkman-init.sh" ]] && source "/home/gpaulo00/.sdkman/bin/sdkman-init.sh"

## Ruby
export PATH="$PATH:$HOME/.rvm/bin"
