#
# Gustavo Paulo <gustavo.paulo.segura@gmail.com>
#
# Zsh Config
#

## initializing
export ZSH_DISABLE_COMPFIX=true
export ZSH=$HOME/.oh-my-zsh
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
  source /etc/profile.d/vte*.sh
fi

# basic
DISABLE_AUTO_TITLE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd/mm/yyyy"

# use powerlevel10k and some plugins
plugins=(git rvm systemadmin zsh-autosuggestions)
ZSH_THEME="powerlevel10k/powerlevel10k"

# use simpler theme on tty
if [ "$TERM" = "linux" ]; then
  ZSH_THEME="fishy"
fi

## run Oh My Zsh!
source $ZSH/oh-my-zsh.sh

## my config
export EDITOR=nvim
export WINEARCH=win32
alias vim=$EDITOR
alias zshconfig="${EDITOR} ~/.zshrc"
alias ohmyzsh="${EDITOR} ~/.oh-my-zsh"

## metasploit framework
export MSFSOURCES="/opt"
alias msfconsole="pushd $MSFSOURCES && ./msfconsole && popd"
alias msfvenom="pushd $MSFSOURCES && ./msfvenom && popd"
alias msfrpc="pushd $MSFSOURCES && ./msfrpc && popd"
alias msfrpcd="pushd $MSFSOURCES && ./msfrpcd && popd"

## fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# programming languagues
## Go
if [ -d "/usr/local/go" ]; then
    export GOPATH=$(/usr/local/go/bin/go env GOPATH)
    export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
fi

## Rust
# export PATH=$PATH:$HOME/.cargo/bin

## Python
if [ -d "$HOME/anaconda3" ]; then
    export PATH="$HOME/anaconda3/bin:$PATH"
    . ~/anaconda3/etc/profile.d/conda.sh
    export PYTHONPATH="$PYTHONPATH:$HOME/anaconda3/lib/python3.6/site-packages"
fi

## JavaScript
export NVM_DIR="$(realpath $HOME)/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

## PHP
export PATH="$PATH:$HOME/.config/composer/vendor/bin"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Gus Config
## Fish-like Path
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
