#
# Gustavo Paulo <gustavo.paulo.segura@gmail.com>
#
# Zsh Config
#

## initializing
export ZSH=/home/gpaulo00/.oh-my-zsh
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
  source /etc/profile.d/vte.sh
fi

# basic
DISABLE_AUTO_TITLE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd/mm/yyyy"

# use powerlevel9k and some plugins
plugins=(git systemadmin zsh-autosuggestions)
ZSH_THEME="powerlevel9k/powerlevel9k"

## configure powerlevel9k
# fish-like path
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

# general
POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_STATUS_VERBOSE="false"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)
POWERLEVEL9K_HOME_ICON=""
POWERLEVEL9K_HOME_SUB_ICON=""
POWERLEVEL9K_FOLDER_ICON=""

# colors
#POWERLEVEL9K_RVM_BACKGROUND="197"
#POWERLEVEL9K_RVM_FOREGROUND="232"
POWERLEVEL9K_OS_ICON_BACKGROUND="249"
POWERLEVEL9K_OS_ICON_FOREGROUND="black"
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="249"
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="black"

## run Oh My Zsh!
source $ZSH/oh-my-zsh.sh

## my config
alias zshconfig="${EDITOR} ~/.zshrc"
alias ohmyzsh="${EDITOR} ~/.oh-my-zsh"

# Go & Java
export GOPATH=$(go env GOPATH)
export PATH=$PATH:/usr/lib/go-tip/bin:$GOPATH/bin
export JAVA_HOME="/usr/lib/jvm/java-8-oracle/"

# NVM
export NVM_DIR="$(realpath $HOME)/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
export PATH="$HOME/.yarn/bin:$PATH"
